FROM node:22

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN echo "source /usr/share/bash-completion/completions/git" >> ~/.bashrc
RUN apt-get update \
    && apt-get install -y sudo lsof socat