services:
  next-app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      BASIC_AUTH_USER: user
      BASIC_AUTH_PASSWORD: password
    volumes:
      - ../:/usr/src/app:cached
    ports:
      - 3001:3001
    stdin_open: true
    tty: true
    networks:
      - kuchikomi-network

networks:
  kuchikomi-network:
    external: true
