services:
  db:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - kuchikomi-network
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    environment:
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_PORT: 3306
    volumes:
      - ..:/usr/src/app:cached
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    networks:
      - kuchikomi-network

volumes:
  db-data:

networks:
  kuchikomi-network:
    external: true