services:
  db:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - kuchikomi-network
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    environment:
      ALLOW_ORIGINS: localhost:3001
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB_NUMBER: 0
      RUN_JOB: false
    volumes:
      - ..:/usr/src/app:cached
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    networks:
      - kuchikomi-network
  redis:
    image: redis:7.2.4
    ports:
      - 6379:6379
    volumes:
      - "./data/redis:/data"
    networks:
      - kuchikomi-network

volumes:
  db-data:

networks:
  kuchikomi-network:
    external: true