steps:
  - name: "gcr.io/cloud-builders/docker"
    args: 
      [
        "build",
        "--tag",
        "${_ARTIFACT_REPOSITORY_IMAGE_NAME}:$SHORT_SHA",
        "--tag",
        "${_ARTIFACT_REPOSITORY_IMAGE_NAME}:latest",
        "--build-arg",
        "MASTER_KEY=$$RAILS_KEY",
        "--build-arg",
        "DATABASE_NAME=${_DATABASE_NAME}",
        "--build-arg",
        "DATABASE_USER=${_DATABASE_USER}",
        "--tag",
        "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}",
        "--file",
        "Dockerfile.prod",
        "--cache-from",
        "${_ARTIFACT_REPOSITORY_IMAGE_NAME}:latest",
        "."
      ]
    secretEnv: ["RAILS_KEY"]

substitutions:
  _DATABASE_NAME: by-terraform
  _DATABASE_USER: by-terraform
  _ARTIFACT_REPOSITORY_IMAGE_NAME: by-terraform

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/${_SECRET_NAME}/versions/latest
    env: RAILS_KEY