steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--platform",
        "linux/amd64",
        "--tag",
        "$_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA",
        "--tag",
        "$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest",
        "--file",
        "Dockerfile.prod",
        "--cache-from",
        "$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest",
        ".",
      ]
    dir: "frontend"
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "--all-tags", "$_ARTIFACT_REPOSITORY_IMAGE_NAME"]
    dir: "frontend"
substitutions:
  _REGION: by-terraform
  _ARTIFACT_REPOSITORY_IMAGE_NAME: by-terraform