steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--platform",
        "linux/amd64",
        "--tag",
        "$_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA",
        "--tag",
        "$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest",
        "--build-arg",
        "BASIC_AUTH_USER=${_BASIC_AUTH_USER}",
        "--build-arg",
        "BASIC_AUTH_PASSWORD=${_BASIC_AUTH_PASSWORD}",
        "--file",
        "Dockerfile.prod",
        "--cache-from",
        "$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest",
        ".",
      ]
    dir: "frontend"
  - name: "gcr.io/cloud-builders/docker"
    args: 
      [
        "push",
        "--all-tags",
        "$_ARTIFACT_REPOSITORY_IMAGE_NAME"
      ]
    dir: "frontend"
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: 
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "$_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA",
        "--region" ,
        "$_REGION"
      ]
    dir: "frontend"
substitutions:
  _REGION: by-terraform
  _ARTIFACT_REPOSITORY_IMAGE_NAME: by-terraform
  _SERVICE_NAME: by-terraform
  _BASIC_AUTH_USER: by-terraform
  _BASIC_AUTH_PASSWORD: by-terraform
images:
  - $_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA