steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: 'bash'
    args: 
      [
        "-c",
        "docker build --platform linux/amd64 --tag $_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA --tag $_ARTIFACT_REPOSITORY_IMAGE_NAME:latest --file Dockerfile.prod --cache-from $_ARTIFACT_REPOSITORY_IMAGE_NAME:latest . ",
      ]
    dir: "lhci"
  - name: "gcr.io/cloud-builders/docker"
    args: 
      [
        "push",
        "--all-tags",
        "$_ARTIFACT_REPOSITORY_IMAGE_NAME"
      ]
    dir: "lhci"
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: 
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "$_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA",
        "--region" ,
        "$_REGION"
      ]
    dir: "lhci"
substitutions:
  _REGION: by-terraform
  _ARTIFACT_REPOSITORY_IMAGE_NAME: by-terraform
  _SERVICE_NAME: by-terraform

images:
  - $_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA