/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/comments": {
    /** Get Comments */
    get: {
      responses: {
        /** @description comment found */
        200: {
          content: {
            "application/json": {
                id: number;
                store_name: string;
                prostutite_name: string;
                comment: string;
                publication_date: Record<string, never>;
              }[];
          };
        };
      };
    };
  };
  "/stores": {
    /** Get Stores */
    get: {
      responses: {
        /** @description store found */
        200: {
          content: {
            "application/json": {
                id: number;
                store_name: string;
                address: {
                  prefecture: string;
                  municipality: string;
                };
                home_page: string;
                store_image: string;
              }[];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
