---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/comments":
    get:
      summary: Get Comments
      tags:
      - Comments
      responses:
        '200':
          description: comment found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    store_name:
                      type: string
                    prostutite_name:
                      type: string
                    comment:
                      type: string
                    publication_date:
                      type: string
                  required:
                  - id
                  - store_name
                  - prostutite_name
                  - comment
                  - publication_date
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
