version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  codecov_upload:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - codecov/upload

workflows:
  version: 2
  build:
    jobs:
      - codecov_upload