services:
  db:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_PASSWORD: password
    volumes:
      - ../..:/usr/src/app:cached
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

volumes:
  db-data: