---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/comments":
    get:
      summary: Get Comments
      tags:
      - Comments
      responses:
        '200':
          description: comment found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    store_name:
                      type: string
                    prostutite_name:
                      type: string
                    comment:
                      type: string
                    publication_date:
                      type: date
                  required:
                  - id
                  - store_name
                  - prostutite_name
                  - comment
                  - publication_date
  "/stores":
    get:
      summary: Get Stores
      tags:
      - Stores
      responses:
        '200':
          description: store found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    store_name:
                      type: string
                    address:
                      type: object
                      properties:
                        prefecture:
                          type: string
                        municipality:
                          type: string
                      required:
                      - prefecture
                      - municipality
                    home_page:
                      type: string
                    store_image:
                      type: string
                  required:
                  - id
                  - store_name
                  - address
                  - home_page
                  - store_image
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
