---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/comments":
    get:
      summary: Get Comments
      tags:
      - Comments
      responses:
        '200':
          description: comment found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    store_name:
                      type: string
                    prostutite_name:
                      type: string
                    comment:
                      type: string
                    publication_date:
                      type: date
                  required:
                  - id
                  - store_name
                  - prostutite_name
                  - comment
                  - publication_date
  "/comparison_report":
    get:
      summary: Get Comparison Report
      tags:
      - Comparison Report
      parameters:
      - name: stores
        in: query
        items:
          type: string
        required: true
        schema:
          type: array
      - name: compare_method
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Comparison Report found
          content:
            application/json:
              schema:
                type: object
                properties:
                  report:
                    type: string
                required:
                - report
  "/rooms":
    get:
      summary: Get Rooms
      tags:
      - Rooms
      responses:
        '200':
          description: room list
          content:
            application/json:
              schema:
                type: object
                properties:
                  list:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        name:
                          type: string
                      required:
                      - id
                      - name
                required:
                - list
    post:
      summary: Create Room
      tags:
      - Rooms
      parameters: []
      responses:
        '200':
          description: room created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                required:
                - id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: number
              required:
              - user_id
  "/stores":
    get:
      summary: Get Stores
      tags:
      - Stores
      parameters:
      - name: keyword
        in: query
        schema:
          type: string
      responses:
        '200':
          description: store found
          content:
            application/json:
              schema:
                type: object
                properties:
                  list:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        store_name:
                          type: string
                        address:
                          type: object
                          properties:
                            prefecture:
                              type: string
                            municipality:
                              type: string
                          required:
                          - prefecture
                          - municipality
                        home_page:
                          type: string
                        store_image:
                          type: string
                        open:
                          type: object
                          properties:
                            from:
                              type: string
                              pattern: "(?-mix:^(?:[01]\\d|2[0-3]):[0-5]\\d$)"
                            to:
                              type: string
                              pattern: "(?-mix:^(?:[01]\\d|2[0-3]):[0-5]\\d$)"
                      required:
                      - store_name
                      - address
                      - home_page
                      - open
                required:
                - list
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
