---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/comments":
    get:
      summary: Get Comments
      tags:
      - Comments
      responses:
        '200':
          description: get comments
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
